### ISSUE TITLE
Only show meta:description when available on ruleset page

### ISSUE THREAD

**Issue by E3V3A** [Koodous/Koodous-Angular-Client#2]
Sorry, if this is the wrong place to post. 

Looking at your [rulesets](https://koodous.com/rulesets) on your webpage, they all start with: 
`import "androguard" rule...` which is useless to see there. Instead, and where available, show the `meta: description` text.

**Comment by beakman** [comment]
Thanks you very much @E3V3A for pointing this out! And please, sorry for the delay.
