### ISSUE TITLE
Strings Filter does not work

### ISSUE THREAD

**Issue by wesinator** [Koodous/Koodous-Angular-Client#35]
Firefox 64

**To reproduce:**
 - https://koodous.com/apks/3dcd7c32e9ea74b13590f59e3b91cf284065db5df21a3aa4f455782b7749e710/analysis Strings
 - Type 'CREATE' in filter

Shows loading bar, same strings from before the filter are displayed.

**Expected:** Only shows strings containing filter text

**Comment by beakman** [comment]
Fixed in #36 Thanks @wesinator !
